### ISSUE TITLE
Tried to build, nothing happens

### ISSUE THREAD

**Issue by Bruniiin** [FlavioFS/ParsecSoda#1]
I followed the instructions perfectly and hit Build Solution, after the build failed (it always fails), there was no output, just an empty x64/Release folder. I then did a search through the entire system for ParsecSoda.exe, also nothing.

Update: file not found: C:\Users/**melonsoda**/source\repos\ParsecSoda\x64\Debug\icon.ico - I think the problem may be this?

**Comment by FlavioFS** [comment]
Yes, some people reported that problem to me already. For some reason, Visual studio linked the app icon to the local path from my machine, instead of the relative path to the solution. If you replace the path with the correct one, the error will be gone.

**Comment by FlavioFS** [comment]
Fixed at commit 0641c287182f2a98c9149cc448fa96007f7847a7.

**Comment by FlavioFS** [comment]
Fixed at commit 0641c287182f2a98c9149cc448fa96007f7847a7.
