### ISSUE TITLE
incorrect controller input logos

### ISSUE THREAD

**Issue by rlem0n** [FlavioFS/ParsecSoda#10]
![image](https://user-images.githubusercontent.com/89490145/133201554-cfe6b802-08f3-4103-b178-b5e89c609ebc.png)
I have my controller plugged in and enabled 4 controllers. it shows 2, "player 2 xbox" logos. ik this is a local thing and stuff but it confused meat first.

**Comment by rlem0n** [comment]
I refreshed it and now it shows 2 player 4 xbox 😂😂😂🤣🤣🤣
![image](https://user-images.githubusercontent.com/89490145/133201763-a5cc7d62-9a24-4205-87f7-0e70bbf3633c.png)

**Comment by FlavioFS** [comment]
That is Microsoft, not Soda. Also it is unimportant, just a visual hint that does not affect the actual behaviour of gamepads.
Anyway, it is patched in v.1.0.2 already. I'm closing the issue.
