### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by ImKing-github** [FlavioFS/ParsecSoda#12]
Parabéns Flavio por ter criado um (talvez até o primeiro) programa de streaming para o parsec, é incrível pensar como um brasileiro conseguiu fazer uma coisa que agora, ta quase todo mundo usando, apenas... parabéns!

**Comment by FlavioFS** [comment]
![](https://i.giphy.com/media/GCvktC0KFy9l6/giphy.webp)

**Comment by marcussacana** [comment]
Acho que podia tentar implementar em linux e talz, dado ao fato que o parsec literalmente ignora os outros sistemas

**Comment by FlavioFS** [comment]
1. Aqui não é lugar pra sugestão, isso é no canal #suggestions no Discord.
2. O SDK do Parsec não hospeda em Linux.
Fechando tópico.
