### ISSUE TITLE
[Request] Add Russian localization to the program

### ISSUE THREAD

**Issue by DmitriyPekar** [FlavioFS/ParsecSoda#48]

**Comment by CollinCodez** [comment]
Parsec Soda uses the Parsec SDK, which is made by the Parsec Team. Parsec has to follow US sanctions against Russia, and therefore those affect Parsec Soda as well. So there is nothing we can really do about that.

**Comment by DmitriyPekar** [comment]
> Parsec Soda uses the Parsec SDK, which is made by the Parsec Team. Parsec has to follow US sanctions against Russia, and therefore those affect Parsec Soda as well. So there is nothing we can really do about that.
sadly
