### ISSUE TITLE
My friends connect but they dont have a controller.

### ISSUE THREAD

**Issue by borjita2019** [FlavioFS/ParsecSoda#5]
My friends connect but they dont have a controller, they want to use the keyboard as a gamepad, how do i do that keyboard to gamepad on parsec? i have seen people have the keyboard to gamepad thing on their room.

**Comment by FlavioFS** [comment]
They just have to press a face button (A, B, X, Y) to request a gamepad. Parsec client has its own default mapping from keyboard to gamepad and clients can see it in the overlay button (and Parsec Soda tries to remain compatible with that).

Though that is kinda common sense at this point for old Parsec users, new users may still not know the basics of how Parsec works.

Also do not forget to leave the inputs unlocked (locker symbol must be green).

**Comment by borjita2019** [comment]
![image](https://user-images.githubusercontent.com/63255187/132143715-5fa4b395-f1fd-4570-885b-0880a79e51c3.png)
this is what i want, but idk how

**Comment by FlavioFS** [comment]
They just need to join the room and press one of these colored buttons. That's all.
