### ISSUE TITLE
Audio Pitch issue

### ISSUE THREAD

**Issue by Vasu222** [FlavioFS/ParsecSoda#52]
I have looked everywhere online to see if I could find anything about it because I'm not the only one getting this audio bug. Everything is slightly lower pitch. I just wanted to know is it something I'm doing or is it just the program?

**Comment by Hoverbike51** [comment]
I found a workaround that might help, I only use 48khz and to fix the audio bug, I host my session then i change my spatial sound to disabled or windows sonic or even dolby atmos. The fact of just changing the type of spatial sound changes the audio output in parsec soda, I just have to put the right output again and miraculously the sound does not bug anymore.
This work for me.

**Comment by Vasu222** [comment]
Do you have to do that every time you host?

**Comment by Vasu222** [comment]
Yay it worked also is there a way to make parsec soda auto assign controllers?
