### ISSUE TITLE
How to change to dualshock 4 on parsec soda?

### ISSUE THREAD

**Issue by borjita2019** [FlavioFS/ParsecSoda#6]
title says it all.

**Comment by FlavioFS** [comment]
XInput only right now.

**Comment by borjita2019** [comment]
oh

**Comment by borjita2019** [comment]
i wanted to play smash with 7 more players

**Comment by borjita2019** [comment]
can you add sometime later?

**Comment by FlavioFS** [comment]
![image](https://user-images.githubusercontent.com/4502942/132258466-fdc867c6-32d3-42ac-95a7-385ce1a607f3.png)

It is a massive refactor. But it is already possible to have 8 people playing with 8 XBox controllers.
I don't know how does it apply to Yuzu, but for Cemu the DInput engine can detect the 8 Xbox gamepads.

**Comment by borjita2019** [comment]
> ![image](https://user-images.githubusercontent.com/4502942/132258466-fdc867c6-32d3-42ac-95a7-385ce1a607f3.png)
> 
> It is a massive refactor. But it is already possible to have 8 people playing with 8 XBox controllers. I don't know how does it apply to Yuzu, but for Cemu the DInput engine can detect the 8 Xbox gamepads.

how the turned have tables
