### ISSUE TITLE
[Feature Request] Disable microphone support for windows 11 to fix 100% CPU issue OR fix Microphone Access on win 11

### ISSUE THREAD

**Issue by epicyeeto** [FlavioFS/ParsecSoda#60]
hello, all! I made a comment on an issue a while back and still didn't get a response. so I'm making an issue to see if a Contributor sees this. to fix this simple issue on win 11 is to just disable the microphone support entirely IK is not the best solution but it's the easiest way and I do not have a problem with it since I don't use my microphone on parsec anyways. making a separate version with this fix would be the best way to not interfere with the working version of win 10. another way is to fix the Compatability Access manager (asking for microphone permission) I don't know how to do that as I'm not a dev but that seems to be the best fix possible.

**Comment by FlavioFS** [comment]
I already fixed it this month. Next release should have this matter settled once and for all, along with extra features.
Windows 11 broke the old mic api, so I just replaced the whole thing from scratch.

**Comment by epicyeeto** [comment]
> I already fixed it this month. Next release should have this matter settled once and for all, along with extra features. Windows 11 broke the old mic api, so I just replaced the whole thing from scratch.

thank you so much for working on this!
