### ISSUE TITLE
Controllers not connecting

### ISSUE THREAD

**Issue by MeleeGamer** [FlavioFS/ParsecSoda#61]
I'm trying to connect virtual controllers by clicking on the connect button, but it's not working! They're staying disconnected. I've tried rebooting the controller system, stripping all controllers, everything!

**Comment by FlavioFS** [comment]
Install VigemBus
https://github.com/ViGEm/ViGEmBus/releases

**Comment by MeleeGamer** [comment]
Thank you! That worked.
