### ISSUE TITLE
[feature request] window capture

### ISSUE THREAD

**Issue by mightymariomanlol** [FlavioFS/ParsecSoda#71]
{warning!, these are just random ideas incase its goanna be added to parsec soda!] window capture, basically you go to settings, and its kind of like adapter list and monitor list except u need that for the window capture to work, basically you click on window list 
then u find the process/window u want to capture for only the guests to see, everything else u can monitor while people play on Fullscreen, this is good because most people can't monitor parsec soda and a Fullscreen game at the same time

**Comment by FlavioFS** [comment]
Not doing it. Too complicated and buggy.
Also may trigger anti-cheat apps and ban people from lots of games.
It is basically remaking OBS, too many work hours for a single dev doing for free.

**Comment by mightymariomanlol** [comment]
i mean for it to be kinda like parsec if u add a game, its perfectly fine if u remove this feature request
