### ISSUE TITLE
parsec is not opening at all 

### ISSUE THREAD

**Issue by epicyeeto** [FlavioFS/ParsecSoda#86]
![image](https://user-images.githubusercontent.com/73504007/231846113-b0c48a05-9f6e-4b42-9aab-024e15d84219.png)
hello am trying to boot parsec but it is no longer working fo me now after upgrading to 1.2.8 and just boots a white screen

**Comment by Sponge498** [comment]
i thought i was the only one that was not opening to so its not just you

**Comment by epicyeeto** [comment]
@Sponge498 
i was stupid and could not read the FAQ where this problem is answered
https://github.com/FlavioFS/ParsecSoda/wiki/FAQ-5
